=== hmrc/self-assessment-accounts-api/resources/public/api/conf/3.0/schemas/retrieveBalanceAndTransactions/response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Self Assessment Balance and Transactions",
  "description": "This endpoint enables you to retrieve the overall liability broken down into overdue, currently due (payable), and pending (not yet due) amounts. A National Insurance number must be provided.",
  "type": "object",
  "properties": {
    "balanceDetails": {
      "$ref": "balanceDetails.json"
    },
    "codingDetails": {
      "$ref": "codingDetails.json"
    },
    "documentDetails": {
      "$ref": "documentDetails.json"
    },
    "financialDetails": {
      "$ref": "financialDetails.json"
    }
  },
  "required": [
    "balanceDetails"
  ],
  "additionalProperties": false
}

=== hmrc/self-assessment-accounts-api/resources/public/api/conf/2.0/examples/retrieveBalanceAndTransactions/retrieveBalanceAndTransactionsFullResponse.json
{
  "balanceDetails": {
    "payableAmount": -99999999999.99,
    "payableDueDate": "1920-02-29",
    "pendingChargeDueAmount": -99999999999.99,
    "pendingChargeDueDate": "1920-02-29",
    "overdueAmount": -99999999999.99,
    "bcdBalancePerYear": [
      {
        "taxYear": "2022-23",
        "bcdAmount": 1300.12
      },
      {
        "taxYear": "2020-21",
        "bcdAmount": 1600.12
      }
    ],
    "earliestPaymentDateOverdue": "1920-02-29",
    "totalBalance": -99999999999.99,
    "amountCodedOut": 3456.67,
    "totalBcdBalance": 2600.24,
    "unallocatedCredit": 3456.67,
    "allocatedCredit": 2345.67,
    "totalCredit": 4567.67,
    "firstPendingAmountRequested": 1234.67,
    "secondPendingAmountRequested": 3100.67,
    "availableCredit": 1212.67
  },
  "codingDetails": {
    "taxYearReturn": "2020-21",
    "totalLiabilityAmount": 5009.99,
    "taxYearCoding": "2020-21",
    "coded": {
      "charge": 5009.99,
      "initiationDate": "2021-04-05"
    }
  },
  "documentDetails": {
    "taxYear": "2020-21",
    "documentId": "1455",
    "formBundleNumber": "88888888",
    "creditReason": "Voluntary Payment",
    "documentDate": "2018-04-05",
    "documentText": "ITSA- Bal Charge",
    "documentDueDate": "2021-04-05",
    "documentDescription": "ITSA- POA 1",
    "originalAmount": 5009.99,
    "outstandingAmount": 5009.99,
    "lastClearing": {
      "lastClearingDate": "2018-04-05",
      "lastClearingReason": "Incoming Payment",
      "lastClearedAmount": 5009.99
    },
    "isChargeEstimate": true,
    "chargeHasMultipleItems": true,
    "paymentLot": "AB1023456789",
    "paymentLotItem": "000001",
    "effectiveDateOfPayment": "2021-04-05",
    "latePaymentInterest": {
      "latePaymentInterestId": "1234567890123456",
      "accruingInterestAmount": 5009.99,
      "interestRate": 5.99,
      "interestStartDate": "2020-04-01",
      "interestEndDate": "2020-04-05",
      "interestAmount": 5009.99,
      "interestDunningLockAmount": 5009.99,
      "interestOutstandingAmount": 5009.99
    },
    "amountCodedOut": 5009.99,
    "reducedCharge": {
      "chargeType": "AA",
      "documentNumber": "1234567890123456",
      "amendmentDate": "2018-04-05",
      "taxYear": "2017-18"
    }
  },
  "financialDetails": [
    {
      "taxYear": "2016-17",
      "chargeDetail": {
        "documentId": "12345678901234568",
        "documentType": "1234",
        "documentTypeDescription": "Income Tax Estimate",
        "chargeType": "5678",
        "chargeTypeDescription": "Income Tax Estimate - ITSA"
      },
      "taxPeriodFrom": "2018-08-13",
      "taxPeriodTo": "2018-08-14",
      "contractAccount": "X",
      "documentNumber": "1040000872",
      "documentNumberItem": "XM00",
      "chargeReference": "XM002610011594",
      "originalAmount": 10000,
      "outstandingAmount": 10000,
      "clearedAmount": 10000,
      "accruedInterest": 10000,
      "items": [
        {
          "subItem": "001",
          "dueDate": "2018-08-13",
          "amount": 10000,
          "clearingDate": "2018-08-13",
          "clearingReason": "01",
          "outgoingPaymentMethod": "Payable Order Repayment",
          "isChargeOnHold": false,
          "isEstimatedChargeOnHold": false,
          "isInterestAccrualOnHold": false,
          "isInterestChargeOnHold": false,
          "isReturn": true,
          "paymentReference": "Ab12453535",
          "paymentAmount": 10000,
          "paymentMethod": "Payment",
          "paymentLot": "81203010024",
          "paymentLotItem": "000001",
          "clearingSAPDocument": "3350000253",
          "isChargeEstimate": true
        }
      ]
    }
  ]
}
